server:
  context-path: /client-two
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
spring:
  application:
    name: client-two