server:
  port: 8080
eureka:
 instance:
  statusPageUrlPath: ${server.context-path}/info
  healthCheckUrlPath: ${server.context-path}/health
  hostname: localhost
 client:
   registerWithEureka: false
   fetchRegistry: false
   serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
spring:
  application:
    name: eureka-server